/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopOrdersRouteImport } from './routes/shop.orders'
import { Route as ShopCheckoutRouteImport } from './routes/shop.checkout'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerCertificatesRouteImport } from './routes/seller.certificates'
import { Route as AdminUmkmRouteImport } from './routes/admin.umkm'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminBuyersRouteImport } from './routes/admin.buyers'
import { Route as ShopProductIdRouteImport } from './routes/shop.product.$id'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerCertificatesRoute = SellerCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => SellerRoute,
} as any)
const AdminUmkmRoute = AdminUmkmRouteImport.update({
  id: '/umkm',
  path: '/umkm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuyersRoute = AdminBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AdminRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/seller': typeof SellerRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/umkm': typeof AdminUmkmRoute
  '/seller/certificates': typeof SellerCertificatesRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/shop/product/$id': typeof ShopProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRouteWithChildren
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/umkm': typeof AdminUmkmRoute
  '/seller/certificates': typeof SellerCertificatesRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/seller': typeof SellerIndexRoute
  '/shop/product/$id': typeof ShopProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/seller': typeof SellerRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/umkm': typeof AdminUmkmRoute
  '/seller/certificates': typeof SellerCertificatesRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/shop/product/$id': typeof ShopProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/login'
    | '/register'
    | '/seller'
    | '/shop'
    | '/admin/buyers'
    | '/admin/certificates'
    | '/admin/transactions'
    | '/admin/umkm'
    | '/seller/certificates'
    | '/seller/orders'
    | '/seller/products'
    | '/shop/checkout'
    | '/shop/orders'
    | '/admin/'
    | '/seller/'
    | '/shop/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/login'
    | '/register'
    | '/shop'
    | '/admin/buyers'
    | '/admin/certificates'
    | '/admin/transactions'
    | '/admin/umkm'
    | '/seller/certificates'
    | '/seller/orders'
    | '/seller/products'
    | '/shop/checkout'
    | '/shop/orders'
    | '/admin'
    | '/seller'
    | '/shop/product/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/login'
    | '/register'
    | '/seller'
    | '/shop'
    | '/admin/buyers'
    | '/admin/certificates'
    | '/admin/transactions'
    | '/admin/umkm'
    | '/seller/certificates'
    | '/seller/orders'
    | '/seller/products'
    | '/shop/checkout'
    | '/shop/orders'
    | '/admin/'
    | '/seller/'
    | '/shop/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SellerRoute: typeof SellerRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/orders': {
      id: '/shop/orders'
      path: '/orders'
      fullPath: '/shop/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/certificates': {
      id: '/seller/certificates'
      path: '/certificates'
      fullPath: '/seller/certificates'
      preLoaderRoute: typeof SellerCertificatesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/admin/umkm': {
      id: '/admin/umkm'
      path: '/umkm'
      fullPath: '/admin/umkm'
      preLoaderRoute: typeof AdminUmkmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buyers': {
      id: '/admin/buyers'
      path: '/buyers'
      fullPath: '/admin/buyers'
      preLoaderRoute: typeof AdminBuyersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/product/$id': {
      id: '/shop/product/$id'
      path: '/product/$id'
      fullPath: '/shop/product/$id'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBuyersRoute: typeof AdminBuyersRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUmkmRoute: typeof AdminUmkmRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBuyersRoute: AdminBuyersRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUmkmRoute: AdminUmkmRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SellerRouteChildren {
  SellerCertificatesRoute: typeof SellerCertificatesRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerCertificatesRoute: SellerCertificatesRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

interface ShopRouteChildren {
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopOrdersRoute: typeof ShopOrdersRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopOrdersRoute: ShopOrdersRoute,
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SellerRoute: SellerRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
